PS - group all published instances, add them Task name
pypeclub/OpenPype pull request #1415
Opened 2021-04-27 15:34 UTC by kalisp

Grouped instances will show up together in Loader.

Configurable by `pype-config/presets/plugins/photoshop/publish.json`:
```
{
    "CollectInstances": {
        "group_by_task_name": true
    }
}
```

Closes: https://github.com/pypeclub/client/issues/56

2021-04-27 16:46 UTC, mkolar commented on pype/plugins/photoshop/publish/collect_instances.py
> +                sanitized_task_name = task[0].upper() + task[1:]
I would leave this exactly as the original task. This is a big too magical.

2021-04-27 16:46 UTC, mkolar requested changes
looking good, but please let's not change the capitalisation

2021-04-27 17:25 UTC, mkolar approved these changes

2021-04-28 09:04 UTC, 64qam approved these changes

2021-04-28 11:53 UTC, merged