Maya Hardware support
pypeclub/OpenPype pull request #1553
Opened 2021-05-21 07:27 UTC by tokejepsen

- adds Maya Hardware support to the rendering pipeline. Normally render farms might not support this but because we use the Maya Sequence rendering (https://github.com/tokejepsen/MayaSequence) we can use Maya Hardware to render playblasts on the farm.
- Ensures the renderer is queried on all render layers.

2021-05-21 12:07 UTC, antirotor requested changes
It does work for me ok with one little problem - we are missing image prefix definition in `validate_render_single_camera.py`:
https://github.com/pypeclub/OpenPype/blob/c363adf079ef140b8587f769c4661c644175806c/pype/plugins/maya/publish/validate_render_single_camera.py#L10-L16

we need to add:
```
'mayahardware2': 'defaultRenderGlobals.imageFilePrefix'
```

After that change, it did submitted ok.

2021-05-21 13:00 UTC, tokejepsen commented
> It does work for me ok with one little problem - we are missing image prefix definition in `validate_render_single_camera.py`:
> https://github.com/pypeclub/OpenPype/blob/c363adf079ef140b8587f769c4661c644175806c/pype/plugins/maya/publish/validate_render_single_camera.py#L10-L16
> 
> we need to add:
> 
> ```
> 'mayahardware2': 'defaultRenderGlobals.imageFilePrefix'
> ```
> 
> After that change, it did submitted ok.

Ahh, dunno why that didnt arise in our tests. Fixed now.

2021-05-21 13:21 UTC, antirotor approved these changes

2021-05-25 08:09 UTC, mkolar approved these changes

2021-05-27 19:13 UTC, merged