Crop overscan in Extract Review
pypeclub/OpenPype pull request #1569
Opened 2021-05-24 09:35 UTC by iLLiCiTiT

## Description
- added ability to define Overscan Crop for input in ExtractReview plugin
- input field is string where is possible to define how crop will work
    - value may cause that resolution will be expanded instead of cropped
    - crop may be explicit or relative, in pixels or percents
    - added special percent case `-10%+` (`10` is random number) which says that input resoltuion is 110% of expected output (input width 2200px -> output width 2000px)
    - value may containt 2 values one for width second for height
    - all values are center related == `+300px` will add 150px on both sides and keep center in center
    - filters should only crop or expand resolution (not rescale)

### Example variants with description
| String | Output | Description |
|---|---|---|
| ` `      | 2200px | Empty string keep resolution unchanged. |
| `50%`    | 1100px | Crop 25% of input width on left and right side. |
| `300px`  | 300px | Keep 300px in center of input and crop rest on left adn right. |
| `300`    | 300px | Values without units are used as pixels (`px`). |
| `0px`   | 0px | Invalid value. |
| `+0px`   | 2200px | Keep resolution unchanged. |
| `+300px` | 2500px | Add black pillars of 150px width on left and right side. |
| `-300px` | 1900px | Crop 150px on left and right side |
| `+10%`   | 2420px | Add black pillars of 5% size of input on left and right side. |
| `-10%`   | 1980px | Crop 5% of input size by on left and right side. |
| `-10%+`  | 2000px | Input width is 110% of output width. |

2021-05-25 21:02 UTC, mkolar commented
Syntax for reversing the overscan using `-10%+` us not working. Instead it actually expands the result by 10% while keeping the same resolution.

2021-05-25 21:49 UTC, mkolar requested changes
see comment about the -+ syntax.

Secondly Please move the crop settings above the resolution. They are processed in order, it would be good to set them in order too. 

Lastly, can we make `0` value do nothing instead of being invalid? Same as with resolution if the setting is 0 or empty it should be considered the same - disabled

2021-05-25 22:59 UTC, iLLiCiTiT commented
> see comment about the -+ syntax.

Swapped +/- in code. Fixed.

> Secondly Please move the crop settings above the resolution

Done

> Lastly, can we make 0 value do nothing instead of being invalid?

Done. Additional question, what if output is smaller than 0px? (Small chance but possible...)

2021-05-27 19:01 UTC, mkolar approved these changes

2021-05-27 19:01 UTC, merged