Update poetry lock
pypeclub/OpenPype pull request #1823
Opened 2021-07-14 13:05 UTC by iLLiCiTiT

## Description
Update poetry lock. This is mainly because of acre update.

## Changes
- updated `poetry.lock` file

2021-07-15 11:14 UTC, antirotor requested changes
This is breaking Python 2 hosts because of updated `requests` that is pulling `charset_normalizer` that is using Python 3 syntax. In other words, we can't no longer upgrade `requests` on global level.

I would change it so it updates only `acre` - take latest develop and run:

```
poetry update acre
```

2021-07-15 11:29 UTC, iLLiCiTiT commented
Only `acre` module was updated in `poetry.lock`.

2021-07-15 15:59 UTC, 64qam commented
Tested on Centos and Windows and looks good so far.

2021-07-19 14:58 UTC, mkolar approved these changes

2021-07-19 16:17 UTC, merged