Dynamic modules
pypeclub/OpenPype pull request #1872
Opened 2021-07-28 13:31 UTC by iLLiCiTiT

## Description
- dynamic loading of OpenPype modules

TODO finish description

2021-08-09 10:41 UTC, jezscha requested changes
I am unable to launch Nuke as it is crashing. Hiero is opening but with this Traceback - the same as in Nuke

```
ERROR 12:39:20.844:Hiero(31140): Plugin C:/CODE/__PYPE/OpenPype/openpype/hosts/hiero/startup\Python\Startup\Startup.py could not be loaded: cannot import name load_modules
Traceback (most recent call last):
  File "C:\Program Files\Nuke12.0v1\pythonextensions\site-packages\hiero\core\find_plugins.py", line 42, in loadPluginsFromFolder
    module = imp.load_source( moduleName, p )
  File "C:/CODE/__PYPE/OpenPype/openpype/hosts/hiero/startup\Python\Startup\Startup.py", line 6, in <module>
    avalon.api.install(phiero)
  File "C:\CODE\__PYPE\OpenPype\repos\avalon-core\avalon\pipeline.py", line 111, in install
    config.install()
  File "C:\CODE\__PYPE\OpenPype\openpype\__init__.py", line 47, in decorated
    return func(*args, **kwargs)
  File "C:\CODE\__PYPE\OpenPype\openpype\__init__.py", line 71, in install
    from openpype.modules import load_modules
ImportError: cannot import name load_modules
```

2021-08-09 10:48 UTC, iLLiCiTiT commented
> I am unable to launch Nuke as it is crashing. Hiero is opening but with this Traceback - the same as in Nuke

Thanks. Missing import in `__init__.py`, fixed.

2021-08-09 12:31 UTC, jezscha approved these changes
works

2021-08-23 13:47 UTC, mkolar approved these changes

2021-08-23 17:06 UTC, merged