Nuke: Adding `still` image family workflow
pypeclub/OpenPype pull request #2064
Opened 2021-09-23 13:01 UTC by jakubjezek001

Adding Still image nuke write rendering workflow from creator via publisher to loader.

# Testing notes
1. start Openpype with settings and make sure you are not having any project overides on Anatomy imageio and nuke loadImage
2. select any node in your testing workfile and go to OpenPype Menu / Create / `Create Write Still Image`. Notice the name of subset will be created regarding actual frame on timeline
3. Publish first with local setting in render knob and then with already rendered frame. 
4. Test Validator for rendered frames if you set already rendered frame and it was not rendered yet, it should be alarming your
5. Check published subset in loader and load it into scene. 
6. in Manager set to lower version then it is actually loaded into your workfile. 
7. all should be working as expected ;)

2021-09-23 13:01 UTC, jakubjezek001 commented
Task linked: [PYPE-1844 nuke still image family](https://app.clickup.com/t/6658547/PYPE-1844)

2021-09-23 13:01 UTC, mkolar commented
Task linked: [PYPE-1844 nuke still image family](https://app.clickup.com/t/6658547/PYPE-1844)

2021-09-24 14:11 UTC, mkolar requested changes
Also I'm getting this when I try to create the still 
![image](https://user-images.githubusercontent.com/3333008/134688790-77e4a101-a7fc-47c7-9ec4-2689894b8e46.png)

2021-09-24 16:22 UTC, jakubjezek001 commented
@mkolar did you follow the testing steps? Settings need to me treated as it is in Anatomy. Look if you see there the still write node definition in Nuke nodes ImageIO.

2021-09-29 16:41 UTC, mkolar commented
> @mkolar did you follow the testing steps? Settings need to me treated as it is in Anatomy. Look if you see there the still write node definition in Nuke nodes ImageIO.

Thanks that was exactly it. I wiped my studio default, but project stayed. With that it works exactly as intended. I just think that the ultimate publish shouldn't have the new family, but stick to image, so we don't fragment it as much.

2021-09-30 09:51 UTC, jrsndl approved these changes
All works for me!

2021-09-30 10:13 UTC, jakubjezek001 commented on openpype/hosts/nuke/plugins/create/create_write_still.py
> +    family = "still"
addressed in [`8c53b3f` (#2064)](https://github.com/pypeclub/OpenPype/pull/2064/commits/8c53b3f1ce0129ee91f6d2430138cbb8e91f4c0c)

2021-09-30 10:26 UTC, 64qam commented
The same error as mentioned above

![image](https://user-images.githubusercontent.com/26925793/135438555-0d1f797d-fa47-481f-8b16-276eb68bc000.png)

2021-09-30 11:24 UTC, jakubjezek001 commented
> The same error as mentioned above
> 
> ![image](https://user-images.githubusercontent.com/26925793/135438555-0d1f797d-fa47-481f-8b16-276eb68bc000.png)

did you try this? https://github.com/pypeclub/OpenPype/pull/2064#issuecomment-930347375

2021-10-01 10:29 UTC, 64qam approved these changes
Looks good

2021-10-01 14:02 UTC, mkolar approved these changes

2021-10-01 14:08 UTC, merged