Unreal: JSON Layout Loading support
pypeclub/OpenPype pull request #2066
Opened 2021-09-23 15:28 UTC by simonebarbieri

2021-11-30 09:45 UTC, mkolar commented
@simonebarbieri is this ready for review? I believe it's been in testing production for a couple of weeks now wasn't it?

2021-12-17 18:10 UTC, antirotor reviewed
Tried to test it but I cannot publish layout from Blender:

simple scene:
![image](https://user-images.githubusercontent.com/33513211/146589031-601430a0-2360-4e73-a88f-72e3275b2808.png)

loaded models are alembics produced by Maya.

Publishing layout will error on **Extract Layout**:

![image](https://user-images.githubusercontent.com/33513211/146589150-c1f9b602-eb52-4fdb-83b0-3092a00d10a4.png)

2022-01-27 16:22 UTC, antirotor requested changes
It does work. Can you resolve the conflict so I can merge it? It is there mainly because of code move from avalon to openpype, it should be enough just to move imports

2022-01-28 12:54 UTC, antirotor approved these changes

2022-01-28 12:55 UTC, merged