Tray UI: Message box about missing settings defaults
pypeclub/OpenPype pull request #2080
Opened 2021-09-27 17:35 UTC by iLLiCiTiT

## Changes
- tray will show a message saying that default settings are not set

## How to test
- remove any key from default settings and run tray

2021-09-27 17:35 UTC, mkolar commented
Task linked: [PYPE-1221 Missing defaults in settings](https://app.clickup.com/t/6658547/PYPE-1221)

2021-09-29 15:14 UTC, jakubjezek001 requested changes
looks good

2021-09-29 15:14 UTC, jakubjezek001 commented on openpype/tools/tray/pype_tray.py
> +            "Your OpenPype may not work as expected because have missing"
I had commited a changes for this

2021-09-29 15:14 UTC, jakubjezek001 approved these changes

2021-09-29 15:20 UTC, merged