Style: New fonts in OpenPype style
pypeclub/OpenPype pull request #2256
Opened 2021-11-16 14:32 UTC by iLLiCiTiT

## Description
Current main font of OpenPype style does not work properly in Qt.

## Changes
- removed fonts: Spartan, Montserrat, RobotoMono
- added new fonts: Noto Sans, Noto Sand Mono
- replaced usage of removed fonts with new ones

2021-11-17 19:50 UTC, mkolar commented
The new fonts are much better, especially in terms of alignments, however, all text is now quite a bit smaller. It's to the point of being uncomfortable. I think we should bump the sizes up a bit
![Screenshot_2](https://user-images.githubusercontent.com/3333008/142272112-f62df3a9-a79f-4a98-8d27-10e170f7d8ad.png)
![Screenshot_3](https://user-images.githubusercontent.com/3333008/142272115-acd7ff8f-7449-4ebb-ba25-0a3cc56d6eb2.png)
.

2021-11-17 19:51 UTC, mkolar requested changes
Let's make the font a bit larger please

2021-11-18 11:28 UTC, jakubjezek001 approved these changes
this font looks awesome. Enclosing the look at my ws.
![Screenshot_2](https://user-images.githubusercontent.com/40640033/142407054-7b6eee5e-bd9b-467b-9a0b-2d7540641d21.png)

2021-11-18 13:06 UTC, mkolar approved these changes

2021-11-18 13:08 UTC, merged