Nuke testing class
pypeclub/OpenPype pull request #2364
Opened 2021-12-02 18:10 UTC by kalisp

Implemented pytest testing class for Nuke. 

Pulls prepared testing zip file from GDrive, prepares temporal DBs(avalon, openpype), opens Nuke, publishes basic workfile, compares result.

(in activated {OPENPYPE_ROOT}/.venv)
`{OPENPYPE_ROOT}/.venv/Scripts/python.exe {OPENPYPE_ROOT}/start.py runtests {OPENPYPE_ROOT}/tests/integration/hosts/nuke`

(Contains merged PR for OP-2019)

2021-12-02 18:10 UTC, mkolar commented
Task linked: [OP-2019 Create test publish class for AE](https://app.clickup.com/t/6658547/OP-2019)

2021-12-02 18:10 UTC, mkolar commented
Task linked: [OP-2042 nuke testing class](https://app.clickup.com/t/6658547/OP-2042)

2021-12-02 20:02 UTC, jakubjezek001 commented on openpype/hosts/aftereffects/plugins/publish/closeAE.py
> +from avalon import aftereffects
shouldn't this module be part of other PR?

2021-12-02 20:02 UTC, jakubjezek001 commented on openpype/hosts/aftereffects/plugins/publish/extract_local_render.py
>          self.log.info("staging_dir::{}".format(staging_dir))
this too is not related to Nuke, right?

2021-12-02 20:03 UTC, jakubjezek001 commented on openpype/lib/remote_publish.py
> +def headless_publish(log, close_plugin_name=None, is_test=False):
I believe this is not related either to Nuke or testing in general ;)

2021-12-02 20:05 UTC, jakubjezek001 requested changes
Lot of unrelated changes in Nuke and Testing context of this PR

2021-12-03 09:21 UTC, kalisp commented
Cleaned up files from AE PR

2021-12-03 13:11 UTC, kalisp commented
Comments:
- add possibility to inject application's input arguments -- will be added to test zip similar to `env_var` folder
- add class variable to inject folder with testing data - for easier building of test class, in the future to daisy chain applications
- add implicit possibility of filling `VARIANT` - if empty look for a) latest installed version b) run tests on all installed versions

2021-12-03 17:03 UTC, kalisp commented
All issues after review implemented. 

Mentioned `-x` command line flag seems not to trigger `init.py`, still needs some testing.

2021-12-06 14:53 UTC, jakubjezek001 approved these changes
works

2021-12-10 17:11 UTC, kalisp commented
Added bunch of updates:
- new wrapper class for testing in a host - each test case in a host should extend this one
- reworked db_asserts to run all asserts, created easier method to query
- output folder is set in a better way
- added `test_data_folder`, `app_variant`, `persist` to cli
- fixed test db cleanup
- fixed published folder cleanup
- test case in Nuke finally works

2021-12-13 12:08 UTC, 64qam approved these changes

2021-12-13 12:14 UTC, merged

2021-12-13 12:14 UTC, kalisp commented
All other features will be implemented in next PRs.