TVPaint: Use new publisher exceptions in validators
pypeclub/OpenPype pull request #2435
Opened 2021-12-22 13:22 UTC by iLLiCiTiT

## Brief description
Use new Exception for validation errors inside TVPaint validators.

## Testing notes:
1. Check the xml and their texts
2. OPTIONAL: Enable new publisher
3. OPTIONAL: Start publishing of TVPaint file and go through each validator

2021-12-22 17:05 UTC, mkolar requested changes

2021-12-22 17:05 UTC, mkolar commented on openpype/hosts/tvpaint/plugins/publish/help/validate_layers_visibility.xml
> +*Check layer names for all subsets in list on left side.*
```suggestion
*Check layer names for all subsets in the list on the left side.*
```

2021-12-22 17:05 UTC, mkolar commented
Tiny correction that I noticed, but looking good overall

2022-01-07 13:03 UTC, 64qam approved these changes

2022-01-07 14:15 UTC, merged