Open a published workfile from the "workfiles" interface
pypeclub/OpenPype pull request #2442
Opened 2021-12-23 13:39 UTC by ClementHector

This feature follow up on discussion #2372

This add a checkbox button to the workfiles interface to ask interface to show the published workfiles and open them:

![image](https://user-images.githubusercontent.com/7955673/147226163-da07058a-63a6-4ac2-acfc-80d861631990.png)

The interface use the `workfile` Family publishing profile to find the published filepath. 

## Note

When "published" is checked, the "browse" and "save as" buttons are deactivated since we only want the users to be allowed to open a published workfile

![image](https://user-images.githubusercontent.com/7955673/147226358-1384f1ba-6646-4d0c-a09e-4caeb7359498.png)

2022-01-03 12:42 UTC, iLLiCiTiT commented
> This feature follow up on discussion #2372

Discussion leads to Two step validation.

> The interface use the workfile Family publishing profile to find the published filepath.

I think that published workfile is "backup of source" of published subsets so it should not be allowed to open and modify.
Also I'm not sure if workfiles logic should contain logic related to published stuff. Publish logic is much more complex and published workfile in theory may not be related to any task...

The only way that make sense to me is to "load" the workfile -> Make a loader which will make a copy of published workfile to workdirectory.

2022-01-04 15:09 UTC, mkolar commented
I'd say this is way too dangerous and invites editing of the published workfiles, however, the effect can be achieved in a safer way I believe. 

- if user chooses to open published workfile, switch the list view of the workfiles to the published ones.
- When user chooses a workfile and hits `open`, the file should be copied to the workarea and opened from there
- during the copying the workfiles should be renamed with a suffix `_published` or something similar added to easily identify where it originated from. 

This poses a few question of what context do we load the workfile into? My suggestion would be to load it into currently active one, rather than the one selected in the workfiels app. That would allow for instance latest `layout` to be loaded easily as a starting point for animation scenes.

2022-01-04 15:10 UTC, mkolar requested changes
As mentioned in the previous comment. I believe we should make this a bit safer by copying the file into current working context.

2022-03-18 16:06 UTC, mkolar commented
We will clean this up on our end based on the discussion so it can be merged and closed

2022-04-06 10:30 UTC, closed without merging