Nuke: Merge avalon's implementation int OpenPype
pypeclub/OpenPype pull request #2514
Opened 2022-01-12 11:31 UTC by iLLiCiTiT

## Brief description
Moved implementation of Nuke from avalon to OpenPype.

## Description
Had to do some modifications of code and reorganize few files to avoid recursive imports.

## Testing notes:
1. All nuke features should work as before
- [ ] Check if all creators can be used
- [ ] Check publish plugins (at least if are discovered)
- [ ] Check if event callbacks work as expected (change of context, etc.)

2022-01-12 11:31 UTC, mkolar commented
Task linked: [OP-2358 Move Nuke to OpenPype](https://app.clickup.com/t/6658547/OP-2358)

2022-01-19 15:43 UTC, jakubjezek001 requested changes
When I do Create Render this is happending

```Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype\openpype\tools\creator\window.py", line 430, in _on_create
    data={"variant": variant}
  File "C:\CODE\__PYPE\OpenPype\repos\avalon-core\avalon\pipeline.py", line 922, in create
    with host.maintained_selection():
AttributeError: 'module' object has no attribute 'maintained_selection'```

2022-01-19 15:49 UTC, iLLiCiTiT commented
> When I do Create Render this is happending

Fixed

2022-01-19 16:35 UTC, jakubjezek001 approved these changes

2022-01-19 17:34 UTC, merged