Deadline: Be able to pass Mongo url to job
pypeclub/OpenPype pull request #2616
Opened 2022-01-31 18:09 UTC by iLLiCiTiT

## Brief description
Add option to pass mongo url to deadline job.

## Changes
- added attributes `pass_mongo_url` to `CollectDefaultDeadlineServer` plugin which is used in submitters to define if `OPENPYPE_MONGO` environment is passed to job environments

## Testing notes:
1. Trigger deadline publishing
2. The job (worker) should not need to have set mongo url in keyring or in global environments

2022-01-31 18:09 UTC, mkolar commented
Task linked: [OP-2539 Add openpype mongo environments to deadline](https://app.clickup.com/t/6658547/OP-2539)

2022-01-31 22:03 UTC, BigRoy commented
> The job (worker) should not need to have set mongo url in keyring or in global environments

What's the use case for this? As in, why do we want to pass the mongo URL? Is it just so it doesn't need to be explicitly set on each machine?

We could also do it the other way around and have the default `OPENPYPE_MONGO` value when not defined in a job set in `GlobalJobPreLoad` and use it from a setting on the OpenPype Deadline Plug-in. Similar to how _OpenPype Executables_ is collected? (Which can be done without needing the ingest that into jobs using an Event Plug-in as shown in #2605). Not saying that is better - but just throwing it out there.

---

Also, these code changes really want me to offload the actual deadline submission into its own library function for the Deadline module, just so we have more code re-use across all plug-ins instead of needing to keep them in sync like this, copying and pasting the code to all of them. :D

2022-02-02 09:54 UTC, mkolar commented
>What's the use case for this? As in, why do we want to pass the mongo URL? Is it just so it doesn't need to be explicitly set on each machine?

Exactly, there is a solid pushback against setting them on machines on a few client sites, so this should make it more flexible.

2022-02-02 09:55 UTC, mkolar commented
>Also, these code changes really want me to offload the actual deadline submission into its own library function for the Deadline

very true. @antirotor didn't you start working on that some time ago?

2022-02-03 17:07 UTC, antirotor commented
> very true. @antirotor didn't you start working on that some time ago?

yes but just bits and pieces. Nothing definitive and I agree that it must be done

2022-02-07 12:16 UTC, kalisp requested changes
I think there should be `context.data.get` and not `context.get` , at least according to my testing. 
If not, please revert commit, if this fix is ok, just dismiss review and re-request.

2022-02-07 14:10 UTC, kalisp approved these changes

2022-02-07 14:53 UTC, merged