Fix open workfile on launch in photoshop
pypeclub/OpenPype pull request #2634
Opened 2022-02-02 18:58 UTC by ClementHector

Fixed AVALON_PHOTOSHOP_WORKFILES_ON_LAUNCH environment variable not being retrieved correctly.

2022-02-03 16:56 UTC, kalisp commented
I think `openpype.lib.env_value_to_bool` would be actually better choice.

2022-02-04 09:27 UTC, kalisp requested changes
I think openpype.lib.env_value_to_bool would be actually better choice.

2022-02-04 11:17 UTC, ClementHector commented
I also modified the other getenv!

2022-02-07 09:05 UTC, kalisp approved these changes

2022-02-07 09:05 UTC, merged