Doc: OpenPype Versioning
pypeclub/OpenPype pull request #2794
Opened 2022-02-22 15:27 UTC by ClementHector

A short explanation of the versioning system in OpenPype.

2022-02-22 15:33 UTC, BigRoy requested changes
Additional to the comments, I'd make sure to use OpenPype as name (with both the O and P as a capital letter) for consistency.

2022-02-22 15:33 UTC, BigRoy commented on website/docs/admin_distribute.md
> +The version of openpye is indicated by the variable `__version__` in the file `.\openpype\version.py`
`openpye` -> `openpype`

2022-02-22 15:33 UTC, BigRoy commented on website/docs/admin_distribute.md
> +For studios customizing the source code of Openpype, it is recommended to build by adding a name and a number after the PATCH and not to deploy 3.8.0 from original OpenPype repositoy. For example, yo
`repositoy` -> `repository`

Plus, missing period at the end of the sentence.

2022-02-22 19:41 UTC, BigRoy approved these changes
Only note I'd have is to end the sentences with a period (`.`). 

Other than that, I'll leave this for further review by someone from the OpenPype team. Probably @mkolar would be a good fit to check?

2022-02-23 07:44 UTC, mkolar approved these changes

2022-02-23 07:46 UTC, mkolar commented on website/docs/admin_distribute.md
> +OpenPype version control is based on semantic versioning
```suggestion
OpenPype version control is based on semantic versioning.
```

2022-02-23 07:46 UTC, mkolar commented on website/docs/admin_distribute.md
> +The version of OpenPype is indicated by the variable `__version__` in the file `.\openpype\version.py`
```suggestion
The version of OpenPype is indicated by the variable `__version__` in the file `.\openpype\version.py`.
```

2022-02-23 07:46 UTC, mkolar commented on website/docs/admin_distribute.md
> +See https://semver.org/ for more details
```suggestion
See https://semver.org/ for more details.
```

2022-02-23 07:46 UTC, mkolar commented on website/docs/admin_distribute.md
> +For studios customizing the source code of OpenPype, a practical approach could be to build by adding a name and a number after the PATCH and not to deploy 3.8.0 from original OpenPype repository. Fo
```suggestion
For studios customizing the source code of OpenPype, a practical approach could be to build by adding a name and a number after the PATCH and not to deploy 3.8.0 from original OpenPype repository. For example, your builds will be: `3.8.0-yourstudio.1` < `3.8.0-yourstudio.2` < `3.8.1-yourstudio.1`.
```

2022-02-23 07:46 UTC, mkolar commented on website/docs/admin_distribute.md
> +For example OpenPype will consider the versions in this order: `3.8.0-nightly` < `3.8.0-nightly.1` < `3.8.0-rc.1` < `3.8.0` < `3.8.1-nightly.1` <`3.8.1` < `3.9.0` < `3.10.0` < `4.0.0`
```suggestion
For example OpenPype will consider the versions in this order: `3.8.0-nightly` < `3.8.0-nightly.1` < `3.8.0-rc.1` < `3.8.0` < `3.8.1-nightly.1` <`3.8.1` < `3.9.0` < `3.10.0` < `4.0.0`.
```

2022-02-23 07:46 UTC, mkolar commented
Apart from the full stops :)

2022-02-23 10:30 UTC, merged

2022-02-23 10:31 UTC, mkolar commented
thank you