General: Move pipeline constants to OpenPype
pypeclub/OpenPype pull request #2918
Opened 2022-03-18 15:28 UTC by iLLiCiTiT

## Brief description
Move constants from avalon-core repository and change import of `ObjectId`.

## Description
There are two constants in avalon pipeline `AVALON_CONTAINER_ID` and `HOST_WORKFILE_EXTENSIONS`. Also we're using `avalon.io.ObjectId` which will cause issues in future.

## Changes
- moved `AVALON_CONTAINER_ID` and `HOST_WORKFILE_EXTENSIONS` into `openpype/pipeline/constants.py`
    - modified imports related to these variables
- changed imports of `ObjectId` to be imported from `bson` python module

## Testing notes:
1. Loading and updating should work as did
2. Workfile extensions should be loaded (last workfile is added to arguments and workfiles tool can save)
3. ObjectId import should not raise an issue

2022-03-21 11:28 UTC, jakubjezek001 requested changes
I had run `create_env` and did make sure avalon-core related PR was checked out, but this is happening to me. 

```
WARNING:openpype.tools.launcher.window.LauncherWindow:Action launch failed.
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype\openpype\tools\launcher\window.py", line 412, in run_action
    action().process(filtered_session)
  File "C:\CODE\__PYPE\OpenPype\openpype\tools\launcher\actions.py", line 108, in process
    **self.data
  File "C:\CODE\__PYPE\OpenPype\openpype\lib\applications.py", line 365, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "C:\CODE\__PYPE\OpenPype\openpype\lib\applications.py", line 504, in launch
    return context.launch()
  File "C:\CODE\__PYPE\OpenPype\openpype\lib\applications.py", line 1140, in launch
    prelaunch_hook.execute()
  File "C:\CODE\__PYPE\OpenPype\openpype\hooks\pre_global_host_data.py", line 45, in execute
    prepare_context_environments(temp_data)
  File "C:\CODE\__PYPE\OpenPype\openpype\lib\applications.py", line 1528, in prepare_context_environments
    _prepare_last_workfile(data, workdir)
  File "C:\CODE\__PYPE\OpenPype\openpype\lib\applications.py", line 1613, in _prepare_last_workfile
    last_workfile_path = avalon.api.last_workfile(
AttributeError: module 'avalon.api' has no attribute 'last_workfile'
```

2022-03-21 12:41 UTC, iLLiCiTiT commented
> I had run create_env and did make sure avalon-core related PR was checked out, but this is happening to me.

Forgot update OpenPype to latest develop.

2022-03-22 10:41 UTC, 64qam approved these changes

2022-03-22 15:04 UTC, jakubjezek001 approved these changes
works

2022-03-22 15:10 UTC, merged