Maya: Redshift Volume Loader Implement update, remove, switch + fix vdb sequence support
pypeclub/OpenPype pull request #3197
Opened 2022-05-17 15:33 UTC by BigRoy

## Brief description

Improves Redshift Volume VDB loader to actually support updating and removing + also support single file or multiple frames in a sequence

## Additional info

The Loader still loads the volume **without!** a material assigned by default. I was thinking of potentially auto-assigning a simple Volume Material but wasn't sure whether we wanted that in the same namespace + actually auto-remove that material when removing the volume as well.

For now you'll need to just manually assign the shader you'll want to render it with after loading the volume.

## Testing notes:
1. Load a VDB volume into Maya

---

Tested with Maya 2022 + Redshift 3.0.67

2022-05-26 09:03 UTC, m-u-r-p-h-y commented
I'm probably doing something wrong but it seems like path resolution is not working in my case.

- published vdb sequence from houdini
- loaded vdb to Maya

```
>>> Finding presets for maya:load ...
// openpype.pipeline.load.utils : Running 'LoadVDBtoRedShift' on 'shVDB'
// Warning:  [Redshift] Failed to find volume file D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.1001.vdb\22101_shVDB_vdbcacheDefault_v001.0001.vdb. Volume will be empty // 
// Warning:  [Redshift] Failed to find volume file D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.1001.vdb\22101_shVDB_vdbcacheDefault_v001.1001.vdb. Volume will be empty // 
Good bye
```

published vdb sequence is 
`D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.####.vdb`

2022-05-26 09:48 UTC, m-u-r-p-h-y requested changes
I'm probably doing something wrong but it seems like path resolution is not working in my case.

- published vdb sequence from houdini
- loaded vdb to Maya

```
>>> Finding presets for maya:load ...
// openpype.pipeline.load.utils : Running 'LoadVDBtoRedShift' on 'shVDB'
// Warning:  [Redshift] Failed to find volume file D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.1001.vdb\22101_shVDB_vdbcacheDefault_v001.0001.vdb. Volume will be empty // 
// Warning:  [Redshift] Failed to find volume file D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.1001.vdb\22101_shVDB_vdbcacheDefault_v001.1001.vdb. Volume will be empty // 
Good bye
```

published vdb sequence is 
`D:\PROJECTS\murphy_22101\shots\shVDB\publish\vdbcache\vdbcacheDefault\v001\22101_shVDB_vdbcacheDefault_v001.####.vdb`

2022-06-07 12:47 UTC, antirotor requested changes
It happened to me too,

2022-06-07 12:47 UTC, antirotor commented on openpype/hosts/maya/plugins/load/load_vdb_to_redshift.py
> +            filename = os.path.join(path, first)
I think this should fix the issue?

```suggestion
            filename = os.path.join(folder, first)
```

2022-07-01 07:52 UTC, m-u-r-p-h-y approved these changes
managing vdb caches works as expected.

- loading
- up versioning
- removing

Maya2023 Redshift 3.5.04

![image](https://user-images.githubusercontent.com/352795/176850017-cd88d954-430d-4d11-9367-e9d80241fcc6.png)

could not test rendering as we ran out of trial :(

2022-07-01 12:34 UTC, antirotor approved these changes
I've just tested it. The volume loads correctly. Strange thing is that render doesn't match the points in the viewport - it seems like the rendered volume is scaled up, but that might be just my test data - as I can't see anything realted to scale in the code.

2022-07-01 12:34 UTC, merged