Ftrack: Use client query functions
pypeclub/OpenPype pull request #3339
Opened 2022-06-14 15:34 UTC by iLLiCiTiT

## Brief description
Ftrack module is using query functions from [PR](https://github.com/pypeclub/OpenPype/pull/3288) instead of direct use of mongo queries.

## Description
Replaced queries using AvalonMongoDB with using function queries from `openpype.client`. Function `get_versions` can accept version names (versions as integers) in filter args. Added new function `get_archived_assets`, it is questionable if it can be merged into `get_assets` with more specific arguments.

## Testing notes:
- [ ] Run any application
- [ ] Run prepare project action on new project
- [ ] Auto-sync from ftrack should work (event server must be running)
- [ ] Run sync to avalon action (doesn't matter if local of server)
- [ ] Download thumbnails from ftrack to openpype
- [ ] Run delivery action
- [ ] Run delete old versions action
- [ ] Run delete asset/subset action (it would be good to try both variants)
- [ ] Integration of hierarchy to ftrack during editorial publishing
- [ ] Action to fill workfile attribute (this requires some more settings)

### Optional testing
Not sure if these features were working:
- Event user assignment
- RV action

2022-06-20 09:40 UTC, jakubjezek001 requested changes
during Delivery action on AssetVersions, following issue had occured @iLLiCiTiT 

```
Traceback (most recent call last):
  File "C:\CODE\__PYPE\OpenPype\openpype\modules\ftrack\event_handlers_user\action_delivery.py", line 478, in launch
    report = self.real_launch(session, entities, event)
  File "C:\CODE\__PYPE\OpenPype\openpype\modules\ftrack\event_handlers_user\action_delivery.py", line 545, in real_launch
    version_ids = self._get_interest_version_ids(session, entities)
TypeERROR: _get_interest_version_ids() missing 1 required positional argument: 'entities'
```

2022-06-20 09:44 UTC, jakubjezek001 commented
Also, if I select any asset/shot and chose `Delete Asset/Subset` action, it is ignoring the context where it is started from and behaving like I am in Project context. It is listing all available Asset objects within the project.

2022-06-20 14:45 UTC, jakubjezek001 approved these changes
All I was testing was working well and I have ticked ON tested features.

2022-06-21 08:43 UTC, 64qam approved these changes

2022-06-21 09:21 UTC, merged