Handle excluding `model` family from frame range validator.
pypeclub/OpenPype pull request #3370
Opened 2022-06-20 10:48 UTC by Allan-I

## Brief description
This fixes Issue #2562 by excluding the `model` family from having its frameStart and frameEnd attributes validated (which it doesn't have

## Description
The `validate_frame_range.py` currently validates the incorrect subset for published Review instances when there's a nested `model` subset in it.  This fix bypasses the validator check when it detects the family is of `model` instance.

## Testing notes:
1. Create model and then create OP `model` instance.
2. Create camera and then create OP `review` instance.
3. Append model instance subset into review subset.
4. Publish.
5. If frame range is set incorrectly, it should give an error and the validator should be able to repair that error by conforming the review instance frame range to the one set in the mongo document.

2022-06-20 10:56 UTC, BigRoy commented
This doesn't seem like a 'clean fix' and feels rather arbitrary? How come the `model` family is problematic? Wouldn't this e.g. also happen with `mayaScene`, `layout`, `look`, `cameraRig`, `rig` families? Or is it solely due to [`CollectModel` which forces a single frame extraction](https://github.com/pypeclub/OpenPype/blob/8432e94615a75216e7172cf46f1370fff806bf13/openpype/hosts/maya/plugins/publish/collect_model.py#L23-L26)?

Sounds like something that points to another potential deeper issue?

2022-06-21 06:35 UTC, mkolar commented
There are a few problems in play here. Most would be solved by implementing the new publisher in  Maya, so we wouldn't have to hack the whole review system, however, that is just constantly slipping in priorities :(.

@bigroy is right and this is not just an issue with model, but anything that get's nested under a review set inside maya. Right now, it really poses two questions. 

1. Should model instance inherit the review framerange, or keep it's own? 
2. Does it make sense to validate frame ranges whatsoever for publishes that are not shot based?

For 1. I'd say that the review framerange should be propagated to the model (or other nested instance) so that it can be properly validated, if required. 

as for 2. we should probably just expose the families attribute to settings, so the studio can choose not to validate frameranges on a set of families for themselves.

2022-06-21 08:11 UTC, BigRoy commented
> For 1. I'd say that the review framerange should be propagated to the model (or other nested instance) so that it can be properly validated, if required.

This sounds unwanted since it opens up for motion/multiple time samples to make it's way into the model `.abc` in the Extract Alembic.

> Does it make sense to validate frame ranges whatsoever for publishes that are not shot based?

Good question. I personally think it's not necessarily only a Shot validation. Maybe at best the Project Manager could also have a state where start/end frame is NOT SET like a boolean stating "use frame range".

2022-06-21 08:26 UTC, mkolar commented
>Good question. I personally think it's not necessarily only a Shot validation. Maybe at best the Project Manager could also have a state where start/end frame is NOT SET like a boolean stating "use frame range".

True, however, I'm not sure it's worth doing it in v3 data model now.  In v4 there is differentiation between asset types and they can technically have empty values on attributes, which will make this a lot easier. 

>This sounds unwanted since it opens up for motion/multiple time samples to make it's way into the model .abc in the Extract Alembic.

Also a very good point. But in that case the only option we have now to make it at least functional is to skip validation on certain families which is exactly what this PR attempts. I just think those families should be configurable

2022-06-21 08:41 UTC, mkolar commented on openpype/hosts/maya/plugins/publish/validate_frame_range.py
> +    exclude_families = ["model"]
If we add this to settings, we'll solve the production situation right now and can focus on doing it properly as Roy suggests in v4

2022-06-21 08:43 UTC, BigRoy commented
> Also a very good point. But in that case the only option we have now to make it at least functional is to skip validation on certain families which is exactly what this PR attempts. I just think those families should be configurable

Or could we reverse that logic? Only check `review` instance family frame range if NOT attached to another instance or if another of the families is set to validate with this validator  (e.g. `animation`)?

2022-06-21 21:48 UTC, antirotor commented
Hmm...  to add to it there seems to be probem with Repair Action for render instances (as it is running against non-existent instances in Maya - they are created on-the-fly by collector).

Maybe repair action should run only on those instances that are "physically" present in Maya and have frame range attributes.

2022-06-24 13:25 UTC, mkolar commented
>Or could we reverse that logic? Only check review instance family frame range if NOT attached to another instance or if another of the families is set to validate with this validator (e.g. animation)?

This is a bit limited to pyblish capabilities right now it's checking in `families`, whereas, here it would be beneficial to only go by `family`, I still think that simply excluding `model`, `rig` and maybe a few others that are not time based, would be the best option right now.

2022-06-28 11:28 UTC, antirotor commented on openpype/settings/defaults/project_settings/maya.json
> +            "exclude_families": []
I would move default families from `validate_frame_range.py#30` to here.
```suggestion
            "exclude_families": ["model", "rig", "staticMesh"]
```

2022-06-30 14:07 UTC, m-u-r-p-h-y requested changes
The Frame Range Validator always passes no matter what numbers are entered in Review Instance

![image](https://user-images.githubusercontent.com/352795/176698235-37c1e74c-e3c5-40a8-b390-579f4d74034e.png)

2022-06-30 14:21 UTC, mkolar commented
>The Frame Range Validator always passes no matter what numbers are entered in Review Instance

that's the whole point of the PR. to not validate on models ;)

2022-06-30 14:32 UTC, m-u-r-p-h-y approved these changes
Ohh. I was reading the original Description and was expecting something else.

In this case it works as expected :)

2022-07-04 13:10 UTC, mkolar approved these changes

2022-07-05 06:08 UTC, merged