Menu hiero
pypeclub/OpenPype pull request #3425
Opened 2022-06-28 15:06 UTC by friquette

## Brief description
First sentence is brief description.

## Description
Next paragraf is more elaborate text with more info. This will be displayed for example in collapsed form under the first sentence in a changelog.

## Additional info
The rest will be ignored in changelog and should contain any additional
technical information.

## Documentation (add _"type: documentation"_ label)
[feature_documentation](future_url_after_it_will_be_merged)

## Testing notes:
1. start with this step
2. follow this step

2022-06-28 15:21 UTC, iLLiCiTiT commented on openpype/hosts/hiero/api/launchforhiero.py
> +from openpype.vendor.python.common.scriptsmenu.vendor.Qt import QtWidgets
You don't have to do so explicit imports on vendorized modules.
from scriptsmenu import scriptsmenu
from Qt import QtWidgets
```

2022-07-01 06:58 UTC, iLLiCiTiT commented on openpype/hosts/hiero/api/menu.py
> +add_scripts_menu()
Never call functions in global scope. This should be moved to function `install` in `pipeline.py`.

2022-07-02 20:34 UTC, jakubjezek001 requested changes

2022-07-04 11:37 UTC, iLLiCiTiT commented on openpype/settings/defaults/project_settings/hiero.json
> +    },
There are not schemas for these settings. Also you've created defaults manually, please use settings UI in develop mode to create default settings.
```suggestion
```

### How to run settings UI in develop mode
There is a script `openpype/tools/run_settings`. If you run it you should have available `Modify defaults` checkbox. From that moment if you save settings they will change default settings in json file.
![image](https://user-images.githubusercontent.com/43494761/177146938-3433d218-96bd-43f5-90e0-5f3fe189e1b5.png)

2022-07-04 12:28 UTC, iLLiCiTiT approved these changes
Looks good. @jakubjezek001 please check and merge.

2022-07-08 11:56 UTC, jakubjezek001 approved these changes
Awesome work, thanx!

2022-07-08 12:04 UTC, merged