General: Use query functions in integrator
pypeclub/OpenPype pull request #3563
Opened 2022-07-25 12:47 UTC by iLLiCiTiT

## Brief description
New integrator plugin is using query functions from `openpype.client`.

## Description
Integrator PR was created before query functions were available (legacy integrator is already using them).

## Testing notes:
1. New integrator should work as did before but is using query functions

2022-07-25 16:00 UTC, antirotor requested changes
It is failing with this traceback:

```
Traceback (most recent call last):
  File "C:\Users\annat\Documents\pype\3.0\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Users\annat\Documents\pype\3.0\openpype\plugins\publish\integrate.py", line 214, in process
  File "C:\Users\annat\Documents\pype\3.0\.venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\annat\Documents\pype\3.0\openpype\plugins\publish\integrate.py", line 208, in process
  File "C:\Users\annat\Documents\pype\3.0\openpype\plugins\publish\integrate.py", line 300, in register
TypeError: prepare_version() missing 1 required positional argument: 'project_name'
```

2022-07-25 16:00 UTC, antirotor commented on openpype/plugins/publish/integrate.py
>          version, version_writes = self.prepare_version(instance, subset)
Is this missing argument?

```suggestion
        version, version_writes = self.prepare_version(instance, subset, projet_name)
```

2022-07-25 16:21 UTC, iLLiCiTiT commented on openpype/plugins/publish/integrate.py
>          version, version_writes = self.prepare_version(instance, subset)
Yep, didn't commit that.

2022-07-26 10:17 UTC, kalisp approved these changes
Tested in AE, PS, Nuke

2022-07-26 16:08 UTC, antirotor approved these changes
It works in Maya too, hooray!

2022-07-26 16:16 UTC, merged