Maya: Build workfile by template
pypeclub/OpenPype pull request #3578
Opened 2022-07-27 08:45 UTC by iLLiCiTiT

Modified [source PR](https://github.com/pypeclub/OpenPype/pull/3315). Code was moved from `openpype/lib` into `openpype/pipeline/workfile` to match refactor goals we're working on right now.

## Brief description
Following discussion #2013 and resumption of work from ellipsanime #2202

## Templated Build Workfile

Building a workfile using a template designed by users. Helping to assert homogeneous subsets hierarchy and imports. Template stored as file easy to define, change and customize for production needs.

 **1. Make a template**

Make your template. Add families and everything needed for your tasks. Here is an example template for the modeling task using a placeholder to import a gauge.

![maya-workfile-outliner](https://user-images.githubusercontent.com/7068597/173068950-ce32a332-4fb0-4177-8e02-b21e07169dac.png)

If needed, you can add placeholders when the template needs to load some assets. **OpenPype > Template Builder > Create Placeholder**

![maya-create_placeholder](https://user-images.githubusercontent.com/7068597/173068995-60cdc782-977d-4789-bbbd-46d63a98eec9.png)

- **Configure placeholders**

Fill in the necessary fields (the optional fields are regex filters)

![maya-placeholder_new](https://user-images.githubusercontent.com/7068597/173069025-d9e3f920-e404-44a9-b218-f4cfac611d21.png)

    - Builder type: Wether the the placeholder should load current asset representations or linked assets representations

    - Representation: Representation that will be loaded (ex: ma, abc, png, etc...)

    - Family: Family of the representation to load (main, look, image, etc ...)

    - Loader: Placeholder loader name that will be used to load corresponding representations

    - Order: Priority for current placeholder loader (priority is lowest first, highet last)

- **Save your template**

 **2. Configure Template**

- **Go to Studio settings > Project > Your DCC > Templated Build Settings**
- Add a profile for your task and enter path to your template

![template_build_workfile](https://user-images.githubusercontent.com/7068597/173069081-634fc0cd-530b-478e-9790-bb5a5b8c443e.png)

**3. Build your workfile**

- Open maya

- Build your workfile

![maya-build_workfile_from_template](https://user-images.githubusercontent.com/7068597/173069101-3907f751-b35a-4c25-a368-3bda9fb12896.png)

2022-07-28 08:30 UTC, m-u-r-p-h-y requested changes
when trying to Build workfile from template, there is an error

`# Error: AttributeError: file D:\REPO\OpenPype\openpype\pipeline\workfile\build_template.py line 38: 'MayaHost' object has no attribute '__name__' # `

2022-07-28 10:05 UTC, iLLiCiTiT commented on openpype/pipeline/workfile/abstract_template_loader.py
> +    def __init__(self, node):
I'm not sure what the `node` should represent, is it node in workfile? We should consider different variable name with some docstrings.

2022-07-28 10:07 UTC, iLLiCiTiT commented on openpype/pipeline/workfile/abstract_template_loader.py
> +class AbstractPlaceholder:
This is just me being annoying but we should rename this class at least to `AbstractTemplatePlaceholder` but `WorkfileTemplatePlaceholder` would work too.

2022-07-28 14:24 UTC, iLLiCiTiT commented
Current state adds a lot of stuff we're trying to avoid and remove with OpenPype refactor. So I expect this feature will change in near future a lot and will break backwards compatibility few times.

For example how representations are queried which is against our goal of not using direct mongo queries in code which is at this moment 100% dependent on using mongo syntax.

2022-08-18 08:35 UTC, mkolar approved these changes

2022-08-18 08:36 UTC, merged