Maya: Redshift Skip aov file format check for Cryptomatte
pypeclub/OpenPype pull request #3654
Opened 2022-08-12 09:23 UTC by BigRoy

## Brief description

This fixes #3410 

## Description

The file format check for AOVs is skipped for Cryptomatte AOVs because Redshift always write it as "Cryptomatte (EXR)" format.

## Testing notes:
1. Set up scene with Redshift + Cryptomatte AOV and others
2. Ensure validation works as expected for file format (extension)

2022-08-12 09:24 UTC, BigRoy commented on openpype/hosts/maya/plugins/publish/validate_rendersettings.py
> -                    "redshiftOptions.imageFormat", asString=True)
I've removed the `asString` argument since the returned values were returned as integers anyway.

2022-08-12 09:27 UTC, BigRoy commented
It was mentioned [here](https://github.com/pypeclub/OpenPype/pull/3643#pullrequestreview-1069610148) that the file format error isn't very clear

> **Murphy**: the file format error is not very clear, as the user is not aware of 1 and 6 and what format it actually represents.

We could turn the integer into redshift image format labels (which is what the Attribute Editor shows) or the extensions with this:

```python
from maya import mel

def redshift_get_image_format_ext(index, as_labels=False):
    if as_labels:
        key = "g_redshiftImageFormatLabels"
    else:
        key = "g_redshiftImageFormatExtensions"
    labels = mel.eval("${0}=${0}".format(key))
    return labels[index]
```
These get defined (on Maya launch?) in Redshift's `Plugins/Maya/Common/scripts/redshiftCreateImageFormats.mel`.

2022-09-02 16:32 UTC, antirotor requested changes
> Let me know if I should add it in this PR.

I think we should add it even as static map mapping values to strings and showing it to the artist. Yes, I am traumatized by windows errors like `Error 0x0004a2c12 has occured`...

2022-09-08 21:08 UTC, BigRoy commented
Improved the logged messages to show the readable labels for the image formats:
![afbeelding](https://user-images.githubusercontent.com/2439881/189225919-a7796c5f-3bf8-4402-b103-c6dc36f328b9.png)

---

Additionally squashed some other bugs:
- `cmds.getAttr("defaultRenderGlobals.imageFilePrefix") would return `None` if no value has ever been set, so I added `or ""` to ensure a string value.
- Repair for `defaultRenderGlobals.animation` wasn't implemented - it now is.

2022-09-14 12:20 UTC, antirotor approved these changes
I think it fine now, thanks for that!. Before merging, I would like @m-u-r-p-h-y  to test it too as my current setup is pretty much broken on Redshift side.

2022-09-23 09:08 UTC, m-u-r-p-h-y commented
where is the global file format taken from?

![image](https://user-images.githubusercontent.com/352795/191928042-8d781da9-31d1-4b7e-bec7-f9fdb3d6cc95.png)

2022-09-23 09:14 UTC, BigRoy commented
This validation checks the AOV file format of the **AOV** where the "global setting" is the setting on the Layer itself.
So basically you have:

- OpenPype Settings: Output Image Format - _unrelated to this error actually_
- Redshift Render Settings > Common > Image Format - this is the currently set 'global' file format for the layer.
- Redshift Render Settings > Advanced > AOV - each AOV also has a file format of its own. That is the AOV file format.

2022-09-23 09:44 UTC, m-u-r-p-h-y commented
From my point of view, the wording is actually opposite.

OP settings is set to TIFF
Render Globals is set to TIFF
Beauty AOV is set OpenExr
Cryptomatte is set to OpenExr

so:
AOV file format OpenExr is not matching Global settings TIFF (OP + Render settings)

2022-09-23 09:59 UTC, BigRoy commented
You were right - the formatting was swapped. Fixed.

2022-09-23 10:04 UTC, m-u-r-p-h-y approved these changes
the check is correctly skipping cryptomatte file format check with Redshift renderer

![image](https://user-images.githubusercontent.com/352795/191937880-a27010a6-d51c-4d55-a673-4ab3f47983ce.png)

2022-09-23 10:07 UTC, merged