Scene Inventory: Add subsetGroup column
pypeclub/OpenPype pull request #3658
Opened 2022-08-12 12:29 UTC by BigRoy

## Brief description

This adds a `subsetGroup` column to the Scene Inventory / Manager.

## Description

We tend to group publishes in the Loader (shortcut: `ctrl + g`) to sometimes label things as "extras" or even group them to be "deprecated".
By showing the column in the Manager this is now also much easier to trace to that information.

![afbeelding](https://user-images.githubusercontent.com/2439881/184353831-631c1670-dfc3-48ac-981a-c41ef77e965b.png)

## Additional info

Code might be a bit messy - so please double check. The "icon" for the group is the default group icon. Originally in Avalon groups could be configured on the project to allow custom icons per groups, etc. but that's currently not supported in OpenPype as far as I know. Thus I had chosen for now to just hardcode the icon.

This would be extra useful as soon as better UX for filtering is added to tools - then we could also filter by subset group, etc.

## Testing notes:
1. Load some content with and without subset groups.
2. Check the scene inventory

2022-08-12 12:49 UTC, BigRoy commented on openpype/tools/sceneinventory/window.py
> -        view.setColumnWidth(4, 100)  # namespace
FYI: Namespace column didn't exist - this was actually setting the `loader` column. I felt the default width for the loader column was slightly too small and most loader names got cut off. So I've set the loader column width to 150.

2022-08-17 09:40 UTC, iLLiCiTiT approved these changes
Code looks ok and works. Can someone check it from UX perspective ( @mkolar @antirotor )?

2022-08-17 12:31 UTC, mkolar approved these changes
I would personally just name it `Group` rather than `subsetGroup`. 

In general It's a good idea, however it's becoming painfully obvious that we'll need to implement hiding and unhiding of columns. For example most of clients on support don't actually use this grouping that much and for those it's suddenly and empty column that's there all the time and is never really populated. Hence needless confusion. 

That's more food for though though and I'm happy with merging this.

2022-08-18 08:55 UTC, mkolar requested changes
Let's please tweak the name of the column, then we can merge

2022-08-18 08:55 UTC, mkolar commented on openpype/tools/sceneinventory/model.py
> +               "subsetGroup", "loader", "objectName"]
```suggestion
               "group", "loader", "objectName"]
```

2022-08-18 08:55 UTC, mkolar commented on openpype/tools/sceneinventory/model.py
> +            if column_name == "subsetGroup" and item.get("subsetGroup"):
```suggestion
            if column_name == "group" and item.get("group"):
```

2022-08-18 08:55 UTC, mkolar commented on openpype/tools/sceneinventory/model.py
> +            group_node["subsetGroup"] = subset["data"].get("subsetGroup")
```suggestion
            group_node["group"] = subset["data"].get("subsetGroup")
```

2022-08-18 09:42 UTC, BigRoy commented
@mkolar How about solely updating the header column's name but keeping it the same in the code? :) Somehow I feel `subsetGroup` keeps it linked to the original data attribute name and describes what it is exactly. Or do you feel `group` is clear enough and one should now that these relate to the subset instead of the version or representation?

2022-08-18 09:44 UTC, BigRoy commented on openpype/tools/sceneinventory/window.py
> +        view.setColumnWidth(4, 120)  # subsetGroup
```suggestion
        view.setColumnWidth(4, 120)  # group
```

2022-08-23 13:54 UTC, iLLiCiTiT commented
@mkolar are you ok with current state?

2022-09-02 16:25 UTC, antirotor approved these changes

2022-09-08 11:55 UTC, mkolar approved these changes

2022-09-08 11:56 UTC, merged