Maya: remove invalid prefix token for non-multipart outputs
pypeclub/OpenPype pull request #3981
Opened 2022-10-13 14:42 UTC by antirotor

## Fix

This is fixing image prefixes for Vray and Redshift to not add `<aov>` token for outputs that are multipart (merged aovs).

### Testing

Submit render to Deadline with merged AOVs from vray or redshift.

Close #3956

2022-10-13 15:39 UTC, m-u-r-p-h-y requested changes
tested withm2023.2 and redshift

with multipart exr enabled it still sets `_<aov>` token for the output image 

![image](https://user-images.githubusercontent.com/352795/195642040-a9fc7ddf-c4b0-4b4a-8954-30c8ce9224eb.png)

2022-10-17 10:58 UTC, LiborBatek commented
Just tested it in with #3954 branch and it works normally (fixes it)....giving it just ```<name>.####.exr`` not nay <AOV> tokens when using multichannel exr format.

Im just not sure if these PRs should be joined together or?

2022-10-17 11:55 UTC, BigRoy commented
> Im just not sure if these PRs should be joined together or?

They should, yes.

This one fixes what the expected output is for the renderer in the situations where multipart EXR is enabled.
The other fixes what is passed to Deadline in the case multipart EXR is disabled.

2022-10-18 12:18 UTC, antirotor commented
I've merged it together. One PR to rule them all.

2022-10-19 06:37 UTC, m-u-r-p-h-y commented
Redshift has actually two multipart options, not very well documented and making the whole thing a true nightmare

![image](https://user-images.githubusercontent.com/352795/196479414-61498a3b-fa31-4739-beb9-7efbc162ade3.png)

redshiftOptions.exrForceMultilayer
redshiftOptions.exrMultipart

It seems we only take into account the first one, which is the only way as with all other combinations multipart + individual aov output settings it is nearly impossible to control.

2022-10-19 06:56 UTC, m-u-r-p-h-y approved these changes
It is good to go, In case of specific combinations of multipart option and per aov image tokens, user can always fall back with disabling the validator as it is really difficult to account for all possible combinations,

2022-10-19 09:55 UTC, merged