bugfix/image plane load error
pypeclub/OpenPype pull request #4222
Opened 2022-12-13 15:34 UTC by moonyuet

## Brief description
Fix the image plane load error

## Description
Fix the bugs and remove some attributes according to https://github.com/pypeclub/OpenPype/issues/3256

## Additional info
No additional info

## Testing notes:
1. Openpype -> Load and select exr sequence
2. right mouse click to load the exrs as image plane sequence
3. create a new camera

2022-12-14 14:36 UTC, LiborBatek commented
Following the testing steps, it shows this error msg:
![image](https://user-images.githubusercontent.com/112623825/207623747-63603f71-01bd-4619-8b86-caa6e49007b5.png)

however the image sequence get connected to the selected cam (chosen during the loading action co connect imagePlane to my shot cam)
![image](https://user-images.githubusercontent.com/112623825/207624095-39fa360b-fb54-4d76-9610-72235fcd73e2.png)

2022-12-14 14:40 UTC, LiborBatek commented
gives me the error even when creating new camera during loading action of imagePlane not trying to attach it to the existing camera (creating new one)
![image](https://user-images.githubusercontent.com/112623825/207625711-8c16f203-92a4-4761-b599-64d77e3d3ec3.png)

2022-12-15 12:49 UTC, moonyuet commented
> gives me the error even when creating new camera during loading action of imagePlane not trying to attach it to the existing camera (creating new one) ![image](https://user-images.githubusercontent.com/112623825/207625711-8c16f203-92a4-4761-b599-64d77e3d3ec3.png)
I have updated the PR to fix the setAttr issue. This could be because time1 node, which connects to the frameExtension of the image plane, doesn't allow to be deleted in maya. I can only disconnect the nodes instead of deleting it.

2022-12-16 07:52 UTC, LiborBatek requested changes
The error with ```frame.extension``` is not showing anymore so its fixed but there is still other issue with ```frame offset``` being wrong set to ```1000```.
![PR4222_imagePlane_offset01](https://user-images.githubusercontent.com/112623825/208049320-a4d8438e-4d14-4142-9f4e-e527bee75425.jpg)
When manually set to correct value (zero) the image sequence being correctly set and visible.
![image](https://user-images.githubusercontent.com/112623825/208049675-77860ee9-f5c7-4f92-9969-6a18f079c7cf.png)
Could be also just an issue in ```maya2023``` not ```maya2022```. 
I think its necessary to keep default ```frame offset``` at zero value.

2022-12-16 08:28 UTC, LiborBatek commented
Tested it again  and  ```frame offset``` being set to ```1000``` in ```maya2022``` it shows image seq correctly and behaves differently than in ```maya2023``` were the image seq is not visible.  Seems like maya bug to me which was fixed in maya2023. I propose to keep the offset at zero by defaults.

2022-12-16 09:13 UTC, m-u-r-p-h-y commented
@LiborBatek can you check all items mentioned in the original issue https://github.com/pypeclub/OpenPype/issues/3256

2022-12-16 10:13 UTC, moonyuet commented
> Tested it again in `maya2022` `frame offset` being set to `1000` it shows image seq despite the offset value (it shouldnt be visible because of that offset) and behaves differently than in `maya2023` were the image seq is not visible as its out of frame range (seq 1001-1005 being offset by another 1000). Seems like maya2022 bug to me which was fixed in maya2023. Anyways I propose to keep/set the offset at zero by defaults. User can offset it manually when needed...

I will remove or set the frameoffset to zero but maybe need to wait because currently i can't really commit to the code and it seems that I dont have the access right to push the latest codes to the PR

2022-12-16 15:51 UTC, LiborBatek approved these changes
Did all tests in ```maya2022``` and ```maya2023``` now all correct.  ```frame offset``` being kept at ```zero``` value. Also tested to load multiple imagePlanes on the same ```camera``` and all worked fine.
Went through old PRs to see if anything was not left out for consideration. Seems ok to me.

2022-12-20 10:15 UTC, m-u-r-p-h-y requested changes
The cancel button is still not working
![image](https://user-images.githubusercontent.com/352795/208642000-8143123f-4ac8-45a3-8ef9-276112ff159a.png)


```
Traceback (most recent call last):
  File "D:\REPO\OpenPype\openpype\tools\loader\widgets.py", line 1578, in _load_representations_by_loader
    options=options
  File "D:\REPO\OpenPype\openpype\pipeline\load\utils.py", line 299, in load_with_repre_context
    return loader.load(repre_context, name, namespace, options)
  File "D:\REPO\OpenPype\openpype\hosts\maya\plugins\load\load_image_plane.py", line 112, in load
    camera = camera_names[window.camera]
KeyError: None
```

2022-12-20 11:04 UTC, m-u-r-p-h-y reviewed
Now there is no error appearing after pressing the Cancel button, but nothing is happening, the dialog is still there.

2022-12-20 15:37 UTC, m-u-r-p-h-y approved these changes
the `Cancel` button works now . . .    :)

2022-12-20 16:08 UTC, iLLiCiTiT commented on openpype/hosts/maya/plugins/load/load_image_plane.py
> +                pass
```suggestion
            camera = camera_names.get(window.camera)
```

2022-12-22 15:23 UTC, merged